# Generated by Django 5.2.13 on 2026-05-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_logrequest_intrusionalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('scan_type', models.CharField(default='fast', max_length=16)),
                ('selected_modules', models.JSONField(default=list)),
                ('ports', models.CharField(blank=True, max_length=128)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('command', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('timeout', 'Timeout'), ('error', 'Error')], default='queued', max_length=16)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scan_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='scanner.scanresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
